version: '3.8'

services:
  app:
    image: hydr/lider-auth # Use the pre-built Docker image instead of building
    ports:
      - '3000:3000' # Map port 3000 on the host to port 3000 in the container
    environment:
      - APP_LEVEL=production
      - PORT=3000
      - FALLBACK_LANGUAGE=tr
    env_file: # Load environment variables from .env file
      - .env
    volumes:
      - ./ldap-config.txt:/usr/src/app/config/ldap/ldap-config.txt
      #change for production /home/pardus/pulsart/ this part
      - /home/pardus/pulsart/server.cert.pem:/usr/src/app/server.cert.pem
      - /home/pardus/pulsart/server.key-pk8.pem:/usr/src/app/server.key-pk8.pem
    command: npm start # Override the default command if necessary
